#!/bin/bash

if [ $# -eq 0 ]; then
echo "USAGE: backup [file]";
exit
else

# $1 should be the folder name of the world that needs backed up
NOW=$(date +"%m-%d-%y.%H%M")
FILE=$1
NEWDIR=$FILE.$NOW

CURRENTPATH=~/FTB/Damascus_Homeworld/$1
BACKUPPATH=~/FTB/Damascus_Homeworld/backups/$NEWDIR

mkdir $BACKUPPATH
cp -rfv $CURRENTPATH $BACKUPPATH
fi

